name: Verify Konami agendas contract tests - master branch

on:
  repository_dispatch:
    types: [pact_changed]

env:
  MVN_ARGUMENTS: -B -Djavax.net.ssl.trustStore=/etc/pki/ca-trust/extracted/java/cacerts -Dmaven.wagon.http.ssl.allowall=true

jobs:
  verify-contract-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mock-test-profile: [ local ]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: 'Bearer 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'

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          overwrite-settings: false
          cache: 'maven'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.8.1

      - name: Compile Konami All Day Agendas service
        run: mvn $MVN_ARGUMENTS clean install -DskipTests

      - name: Run Konami All Day Agendas service
        run: mvn $MVN_ARGUMENTS -Prun -e exec:exec -f konami-all-day-agendas-provider-service/pom.xml

      - name: Run verification contract tests
        run: mvn $MVN_ARGUMENTS -f konami-all-day-agendas-provider-service/pom.xml surefire:test -Dtest="**/*AgendaDataProviderContractTest.java" -Dpact.verifier.publishResults=true -Dpact.provider.branch="MASTER" -Dpact.provider.version=$MVN_PROJ_VERSION+"MASTER" -Dpact.provider.tag="MASTER"

      - name: Publish Contract Tests Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          check_name: Contract Tests Report
          fail_on_failure: true
          require_tests: true
          report_paths: '**/target/surefire-reports/TEST-*.xml'